-- FIX STEP 2: Real Competitor Names (60 brands)
-- CORRECTED: market_share is NUMERIC, not TEXT (no % signs)

DELETE FROM brand_competitors_complete WHERE brand_name IN (
  'PepsiCo', 'Red Bull', 'Monster Energy', 'Nescafé', 'Danone', 'Fiji Water', 'Perrier', 'Gatorade', 'Tropicana', 'Sprite',
  'Mars Inc', 'Nestlé Confectionery', 'Mondelēz', 'Ferrero', 'Lindt', 'Haribo', 'Cadbury', 'Hershey', 'Lay''s', 'Doritos',
  'Olay', 'Gillette', 'Dove', 'L''Oréal', 'Estée Lauder', 'Revlon', 'CoverGirl', 'Maybelline', 'Neutrogena', 'Clinique',
  'Tide', 'Dawn', 'Lysol', 'Clorox', 'Colgate', 'SC Johnson', 'Henkel', 'Method', 'Ecos', 'Surf',
  'McDonald''s', 'Subway', 'Domino''s', 'KFC', 'Chipotle', 'Wendy''s', 'Burger King', 'Taco Bell', 'Pizza Hut', 'Panera Bread',
  'Kraft Heinz', 'General Mills', 'Kellogg''s', 'Nestlé Food', 'Lactalis', 'ConAgra', 'Campbell Soup', 'Unilever Food', 'Tyson Foods', 'Ben & Jerry''s'
);

-- BEVERAGES (30)
INSERT INTO brand_competitors_complete (brand_name, competitor_name, market_position, market_share) VALUES
('Red Bull', 'Monster Energy', 2, 22),
('Red Bull', 'Coca-Cola Energy', 3, 8),
('Red Bull', 'Gatorade', 4, 6),
('Monster Energy', 'Red Bull', 1, 28),
('Monster Energy', 'Gatorade', 3, 12),
('Monster Energy', 'Coca-Cola Energy', 4, 5),
('PepsiCo', 'Coca-Cola Company', 1, 42),
('PepsiCo', 'Keurig Dr Pepper', 3, 18),
('PepsiCo', 'Monster Beverage', 4, 8),
('Sprite', 'Coca-Cola', 1, 35),
('Sprite', 'Fanta', 2, 22),
('Sprite', 'Mountain Dew', 3, 15),
('Gatorade', 'Powerade', 2, 18),
('Gatorade', 'Coconut Water', 3, 12),
('Gatorade', 'Alkaline Water', 4, 5),
('Tropicana', 'Simply Orange', 2, 16),
('Tropicana', 'Minute Maid', 3, 14),
('Tropicana', 'Naked Juice', 4, 8),
('Nescafé', 'Starbucks', 2, 24),
('Nescafé', 'Maxwell House', 3, 12),
('Nescafé', 'Folgers', 4, 10),
('Danone', 'Fage', 2, 15),
('Danone', 'Chobani', 3, 14),
('Danone', 'Siggi''s', 4, 9),
('Fiji Water', 'Evian', 2, 26),
('Fiji Water', 'Voss', 3, 14),
('Fiji Water', 'S.Pellegrino', 4, 12),
('Perrier', 'San Pellegrino', 2, 18),
('Perrier', 'Topo Chico', 3, 12),
('Perrier', 'LaCroix', 4, 8);

-- SNACKS & CONFECTIONERY (30)
INSERT INTO brand_competitors_complete (brand_name, competitor_name, market_position, market_share) VALUES
('Mars Inc', 'Mondelēz', 2, 18),
('Mars Inc', 'Ferrero', 3, 14),
('Mars Inc', 'Hershey', 4, 12),
('Nestlé Confectionery', 'Mars Inc', 1, 22),
('Nestlé Confectionery', 'Ferrero', 3, 16),
('Nestlé Confectionery', 'Lindt', 4, 11),
('Mondelēz', 'Mars Inc', 1, 20),
('Mondelēz', 'Nestlé', 2, 19),
('Mondelēz', 'Ferrero', 4, 10),
('Ferrero', 'Lindt', 2, 14),
('Ferrero', 'Hershey', 3, 13),
('Ferrero', 'Ghirardelli', 4, 7),
('Lindt', 'Ferrero', 1, 15),
('Lindt', 'Godiva', 3, 8),
('Lindt', 'Ghirardelli', 4, 6),
('Haribo', 'Albanese', 2, 22),
('Haribo', 'Trolli', 3, 15),
('Haribo', 'Gummy bears generic', 4, 10),
('Cadbury', 'Hershey', 2, 14),
('Cadbury', 'Mars', 3, 16),
('Cadbury', 'Ferrero', 4, 12),
('Hershey', 'Cadbury', 1, 18),
('Hershey', 'Mars', 2, 17),
('Hershey', 'Nestlé', 3, 14),
('Lay''s', 'Doritos', 1, 18),
('Lay''s', 'Cheetos', 3, 15),
('Lay''s', 'Pringles', 4, 12),
('Doritos', 'Lay''s', 2, 22),
('Doritos', 'Cheetos', 3, 14),
('Doritos', 'Fritos', 4, 8);

-- PERSONAL CARE (30)
INSERT INTO brand_competitors_complete (brand_name, competitor_name, market_position, market_share) VALUES
('Olay', 'Neutrogena', 2, 16),
('Olay', 'Dove', 3, 14),
('Olay', 'Cetaphil', 4, 9),
('Gillette', 'Schick', 2, 28),
('Gillette', 'Bic', 3, 18),
('Gillette', 'Harry''s', 4, 12),
('Dove', 'Cetaphil', 2, 15),
('Dove', 'Olay', 3, 12),
('Dove', 'CeraVe', 4, 10),
('L''Oréal', 'Estée Lauder', 2, 16),
('L''Oréal', 'Shiseido', 3, 12),
('L''Oréal', 'Unilever Beauty', 4, 10),
('Estée Lauder', 'L''Oréal', 1, 18),
('Estée Lauder', 'Shiseido', 3, 11),
('Estée Lauder', 'LVMH Beauty', 4, 9),
('Revlon', 'Maybelline', 2, 24),
('Revlon', 'L''Oréal', 3, 18),
('Revlon', 'CoverGirl', 4, 14),
('CoverGirl', 'Maybelline', 1, 22),
('CoverGirl', 'Revlon', 3, 16),
('CoverGirl', 'L''Oréal', 4, 14),
('Maybelline', 'L''Oréal', 2, 20),
('Maybelline', 'Revlon', 3, 18),
('Maybelline', 'CoverGirl', 4, 16),
('Neutrogena', 'CeraVe', 2, 18),
('Neutrogena', 'Cetaphil', 3, 14),
('Neutrogena', 'Olay', 4, 12),
('Clinique', 'Estée Lauder', 1, 14),
('Clinique', 'Lancôme', 3, 10),
('Clinique', 'MAC', 4, 7);

-- HOUSEHOLD CLEANING (30)
INSERT INTO brand_competitors_complete (brand_name, competitor_name, market_position, market_share) VALUES
('Tide', 'All', 2, 16),
('Tide', 'Persil', 3, 14),
('Tide', 'Gain', 4, 11),
('Dawn', 'Palmolive', 2, 22),
('Dawn', 'Finish', 3, 16),
('Dawn', 'Seventh Generation', 4, 8),
('Lysol', 'Clorox', 1, 24),
('Lysol', 'Febreze', 3, 12),
('Lysol', 'Windex', 4, 10),
('Clorox', 'Lysol', 2, 22),
('Clorox', 'OxiClean', 3, 14),
('Clorox', 'Seventh Generation', 4, 8),
('Colgate', 'Crest', 2, 28),
('Colgate', 'Sensodyne', 3, 16),
('Colgate', 'Tom''s', 4, 9),
('SC Johnson', 'Clorox', 1, 26),
('SC Johnson', 'Seventh Generation', 3, 12),
('SC Johnson', 'Mrs. Meyer''s', 4, 10),
('Henkel', 'Reckitt', 1, 22),
('Henkel', 'Unilever', 3, 18),
('Henkel', 'Clorox', 4, 14),
('Method', 'Seventh Generation', 1, 18),
('Method', 'Mrs. Meyer''s', 3, 16),
('Method', 'Ecos', 4, 14),
('Ecos', 'Method', 1, 16),
('Ecos', 'Seventh Generation', 2, 14),
('Ecos', 'Mrs. Meyer''s', 3, 12),
('Surf', 'Tide', 2, 18),
('Surf', 'All', 3, 16),
('Surf', 'Persil', 4, 12);

-- QSR (30)
INSERT INTO brand_competitors_complete (brand_name, competitor_name, market_position, market_share) VALUES
('McDonald''s', 'Subway', 2, 8),
('McDonald''s', 'Starbucks', 3, 7),
('McDonald''s', 'Wendy''s', 4, 5),
('Subway', 'McDonald''s', 1, 22),
('Subway', 'Chipotle', 3, 9),
('Subway', 'Panera', 4, 6),
('Domino''s', 'Pizza Hut', 2, 18),
('Domino''s', 'Little Caesars', 3, 12),
('Domino''s', 'Papa John''s', 4, 10),
('KFC', 'Chick-fil-A', 2, 16),
('KFC', 'Popeyes', 3, 14),
('KFC', 'Wingstop', 4, 8),
('Chipotle', 'Qdoba', 2, 14),
('Chipotle', 'Panera', 3, 12),
('Chipotle', 'Sweetgreen', 4, 8),
('Wendy''s', 'McDonald''s', 1, 26),
('Wendy''s', 'Burger King', 3, 9),
('Wendy''s', 'Five Guys', 4, 5),
('Burger King', 'McDonald''s', 1, 28),
('Burger King', 'Wendy''s', 2, 12),
('Burger King', 'Five Guys', 4, 6),
('Taco Bell', 'Chipotle', 1, 16),
('Taco Bell', 'Qdoba', 3, 14),
('Taco Bell', 'Del Taco', 4, 10),
('Pizza Hut', 'Domino''s', 1, 22),
('Pizza Hut', 'Papa John''s', 3, 14),
('Pizza Hut', 'Little Caesars', 4, 11),
('Panera Bread', 'Chipotle', 1, 18),
('Panera Bread', 'Sweetgreen', 2, 16),
('Panera Bread', 'Shake Shack', 4, 8);

-- PACKAGED FOOD (30)
INSERT INTO brand_competitors_complete (brand_name, competitor_name, market_position, market_share) VALUES
('Kraft Heinz', 'General Mills', 2, 14),
('Kraft Heinz', 'Mondelēz', 3, 12),
('Kraft Heinz', 'Nestlé', 4, 10),
('General Mills', 'Kellogg''s', 2, 18),
('General Mills', 'Post', 3, 12),
('General Mills', 'Nestlé', 4, 10),
('Kellogg''s', 'General Mills', 1, 22),
('Kellogg''s', 'Post', 3, 14),
('Kellogg''s', 'Quaker', 4, 11),
('Nestlé Food', 'Kraft Heinz', 1, 18),
('Nestlé Food', 'Danone', 3, 16),
('Nestlé Food', 'Lactalis', 4, 12),
('Lactalis', 'Danone', 1, 24),
('Lactalis', 'Kraft Heinz', 3, 14),
('Lactalis', 'Nestlé', 4, 12),
('ConAgra', 'Heinz', 1, 20),
('ConAgra', 'Hunt''s', 3, 16),
('ConAgra', 'Ragu', 4, 12),
('Campbell Soup', 'Progresso', 2, 18),
('Campbell Soup', 'Lipton', 3, 14),
('Campbell Soup', 'Knorr', 4, 10),
('Unilever Food', 'Kraft Heinz', 1, 22),
('Unilever Food', 'Nestlé', 2, 20),
('Unilever Food', 'Danone', 4, 12),
('Tyson Foods', 'Perdue', 2, 18),
('Tyson Foods', 'Pilgrim''s Pride', 3, 16),
('Tyson Foods', 'Sanderson Farms', 4, 10),
('Ben & Jerry''s', 'Häagen-Dazs', 2, 16),
('Ben & Jerry''s', 'Talenti', 3, 12),
('Ben & Jerry''s', 'Blue Bell', 4, 10);

-- Verify
SELECT COUNT(*) as total_competitors FROM brand_competitors_complete;
