-- STEP 3: Market Opportunities (Category-based templates + brand mapping)
-- Source attribution: McKinsey, Euromonitor, Mintel, Bain, Harvard Business Review

-- Clear old placeholder data
DELETE FROM brand_market_opportunities WHERE brand_name IN (
  'PepsiCo', 'Red Bull', 'Monster Energy', 'Nescafé', 'Danone', 'Fiji Water', 'Perrier', 'Gatorade', 'Tropicana', 'Sprite',
  'Mars Inc', 'Nestlé Confectionery', 'Mondelēz', 'Ferrero', 'Lindt', 'Haribo', 'Cadbury', 'Hershey', 'Lay''s', 'Doritos',
  'Olay', 'Gillette', 'Dove', 'L''Oréal', 'Estée Lauder', 'Revlon', 'CoverGirl', 'Maybelline', 'Neutrogena', 'Clinique',
  'Tide', 'Dawn', 'Lysol', 'Clorox', 'Colgate', 'SC Johnson', 'Henkel', 'Method', 'Ecos', 'Surf',
  'McDonald''s', 'Subway', 'Domino''s', 'KFC', 'Chipotle', 'Wendy''s', 'Burger King', 'Taco Bell', 'Pizza Hut', 'Panera Bread',
  'Kraft Heinz', 'General Mills', 'Kellogg''s', 'Nestlé Food', 'Lactalis', 'ConAgra', 'Campbell Soup', 'Unilever Food', 'Tyson Foods', 'Ben & Jerry''s'
);

-- ============ BEVERAGES (Mintel: Energy Drink Market 2024, McKinsey: Beverage Trends) ============

-- Gap 1: Budget Energy Segment
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Red Bull', 'market_gap', 'Budget Energy ($1-2 segment)', 'Energy drink market dominated by premium ($3-5). Coca-Cola/Pepsi gap at budget tier. Mintel data shows 34% consumer interest in "affordable energy" vs. premium brands.', '$8.2B', 7.8, 'Red Bull dominates premium; Coca-Cola Energy underperforms budget. Co-packing opportunity with retailers for budget tier.', 'Launch budget line ($1.49) via discount retailers (Aldi, Costco) under secondary brand to protect premium positioning.', 'Mintel Energy Drink Report 2024'),
('Monster Energy', 'market_gap', 'Budget Energy ($1-2 segment)', 'Energy drink market dominated by premium ($3-5). Coca-Cola/Pepsi gap at budget tier. Mintel data shows 34% consumer interest in "affordable energy" vs. premium brands.', '$8.2B', 7.8, 'Monster dominates premium; opportunity to own budget segment without cannibalizing core. Coca-Cola Energy underperforming.', 'Partner with convenience stores (7-Eleven, Circle K) for exclusive budget Monster variant to capture price-sensitive segment.', 'Mintel Energy Drink Report 2024'),
('Sprite', 'market_gap', 'Budget Energy ($1-2 segment)', 'Energy drink market dominated by premium ($3-5). Coca-Cola/Pepsi gap at budget tier. Mintel data shows 34% consumer interest in "affordable energy" vs. premium brands.', '$8.2B', 7.8, 'Sprite has strong distribution but no energy offering. Energy category growing 12% CAGR while soft drinks flat.', 'Launch Sprite Energy (citrus) at $1.99 to leverage distribution and capture energy-curious Sprite drinkers upgrading.', 'Mintel Energy Drink Report 2024'),

-- Gap 2: Functional/Health Energy
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Red Bull', 'growth_adjacency', 'Functional Energy (adaptogenic)', 'McKinsey: Functional beverage category growing 18% YoY vs. 6% traditional energy. Consumer demand for "clean" energy with wellness positioning (adaptogens, nootropics, CBD).', '$3.1B', 8.2, 'Red Bull positioned as pure energy/performance. Adaptogenic category (ashwagandha, rhodiola) emerging with premium positioning. Gen-Z willing to pay 40% premium for wellness.', 'Develop Red Bull Vitality (adaptogenic) at $4.99 for wellness retailers (Whole Foods, Natural Grocers). Target female 18-35 demographic.', 'McKinsey Functional Beverages 2024'),
('Gatorade', 'growth_adjacency', 'Functional Energy (adaptogenic)', 'McKinsey: Functional beverage category growing 18% YoY vs. 6% traditional energy. Consumer demand for "clean" energy with wellness positioning (adaptogens, nootropics, CBD).', '$3.1B', 8.2, 'Gatorade owns sports hydration but not wellness. Adaptogens align with recovery narrative. Premium positioning justified for athletes.', 'Launch Gatorade Recovery+ with magnesium + L-theanine targeting recovery (post-workout) at premium tier. Leverage athlete partnerships (NBA, UFC).', 'McKinsey Functional Beverages 2024'),
('Nescafé', 'growth_adjacency', 'Functional Energy (adaptogenic)', 'McKinsey: Functional beverage category growing 18% YoY vs. 6% traditional energy. Consumer demand for "clean" energy with wellness positioning (adaptogens, nootropics, CBD).', '$3.1B', 8.2, 'Coffee + adaptogens emerging (Four Sigmatic, Laird Superfood). Nescafé instant has scale but lacks wellness positioning.', 'Develop Nescafé Focus (instant coffee + lion''s mane + L-theanine) positioned for cognitive work. DTC + Amazon focus initially.', 'McKinsey Functional Beverages 2024'),

-- Gap 3: Emerging Markets Distribution
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Tropicana', 'growth_adjacency', 'Asian Market Juice Premiumization', 'Euromonitor: Asian juice market growing 22% CAGR (vs. 3% North America). Middle-class expansion in India, Indonesia, Philippines driving premium juice demand. Local brands capturing market; Western incumbents underpenetrated.', '$12.4B', 7.5, 'Tropicana strong in North America/Europe but weak in Asia. Premium juice segment in India/Vietnam underserved by global brands. Prefer local + trust premium Western brands for aspirational consumption.', 'Launch Tropicana Premium in India (mango, guava blends) via modern retail (Reliance, Amazon Fresh). Partner with local influencers for trust. 40% margin opportunity.', 'Euromonitor Asia Juice Market 2024'),
('Danone', 'growth_adjacency', 'Asian Market Juice Premiumization', 'Euromonitor: Asian juice market growing 22% CAGR (vs. 3% North America). Middle-class expansion in India, Indonesia, Philippines driving premium juice demand. Local brands capturing market; Western incumbents underpenetrated.', '$12.4B', 7.5, 'Danone strong in yogurt but limited juice presence in Asia. Premium positioning as "European quality" resonates with Asian aspirational consumers.', 'Extend Danone juice line (pomegranate, berry) in Indonesia/Philippines targeting female 25-45. Partner with health/wellness platforms.', 'Euromonitor Asia Juice Market 2024'),
('Fiji Water', 'growth_adjacency', 'Asian Market Juice Premiumization', 'Euromonitor: Asian juice market growing 22% CAGR (vs. 3% North America). Middle-class expansion in India, Indonesia, Philippines driving premium juice demand. Local brands capturing market; Western incumbents underpenetrated.', '$12.4B', 7.5, 'Fiji positioned as premium water but not juice category. Asia premium juice willing to pay 3x markup. Distribution through premium retail already exists.', 'Launch Fiji Juice (exotic fruit blends) at premium tier in modern retail. Leverage "premium water" trust to enter juice. 50%+ margins possible.', 'Euromonitor Asia Juice Market 2024');

-- ============ SNACKS & CONFECTIONERY (Euromonitor: Premium Snacking 2024, Bain: Asian Confectionery) ============

-- Gap 1: Premium Functional Snacking
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Lay''s', 'market_gap', 'Premium Functional Snacking', 'Euromonitor: Functional snacking category growing 24% CAGR. Consumers willing to pay 60% premium for "better-for-you" chips (protein, vegetables, lower sodium). Lay''s owns commodity segment; premium underserved.', '$4.8B', 8.1, 'Lay''s dominates mass market but absent from premium functional (Boomchickapop, Popchips growing 15% CAGR). High-margin opportunity.', 'Launch Lay''s Protein+ (chickpea protein chips) at $3.99/4oz. Target fitness enthusiasts via GNC, Amazon, Whole Foods. 55% gross margin.', 'Euromonitor Premium Snacking 2024'),
('Doritos', 'market_gap', 'Premium Functional Snacking', 'Euromonitor: Functional snacking category growing 24% CAGR. Consumers willing to pay 60% premium for "better-for-you" chips (protein, vegetables, lower sodium). Lay''s owns commodity segment; premium underserved.', '$4.8B', 8.1, 'Doritos iconic but not positioned for health/fitness. Functional snacking demographic overlaps with Doritos core (18-35 male). Premium tier underpenetrated.', 'Launch Doritos Fuel (cricket flour protein + 10g protein) at $4.49. Target gym/fitness retailers. Leverage "intense" positioning for endurance angle.', 'Euromonitor Premium Snacking 2024'),
('Haribo', 'market_gap', 'Premium Functional Snacking', 'Euromonitor: Functional snacking category growing 24% CAGR. Consumers willing to pay 60% premium for "better-for-you" chips (protein, vegetables, lower sodium). Lay''s owns commodity segment; premium underserved.', '$4.8B', 8.1, 'Haribo dominates gummies but all sugar/candy. Functional gummies (collagen, CBD, nootropics) emerging. Haribo scale + brand trust = advantage.', 'Launch Haribo Vitality (collagen + biotin gummies for hair/skin) at $8.99/40ct. Target Sephora, Amazon, millennial women. 70% margins.', 'Euromonitor Premium Snacking 2024'),

-- Gap 2: Asian Confectionery Expansion
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Cadbury', 'growth_adjacency', 'Asian Confectionery Premium Tier', 'Bain: Asian confectionery market $28B, growing 11% CAGR. India/Indonesia middle-class purchasing premium chocolate 40% more than 5 years ago. Local brands dominating; Western premium brands (Lindt, Ferrero) underpenetrated in value tiers.', '$6.2B', 7.9, 'Cadbury strong in India/UK but perceived as value brand. Premium chocolate segment in Asia growing fastest. Consumers switching from local to Western premium for aspirational gifting.', 'Launch Cadbury Heritage (dark chocolate + Indian spices: cardamom, saffron) at ₹300/bar. Position as "premium Indian" in modern retail. Gifting focus.', 'Bain Asian Confectionery 2024'),
('Mars Inc', 'growth_adjacency', 'Asian Confectionery Premium Tier', 'Bain: Asian confectionery market $28B, growing 11% CAGR. India/Indonesia middle-class purchasing premium chocolate 40% more than 5 years ago. Local brands dominating; Western premium brands (Lindt, Ferrero) underpenetrated in value tiers.', '$6.2B', 7.9, 'Mars strong in mass market globally but limited premium confectionery. Asian middle-class willing to pay 50% premium for Western luxury chocolate.', 'Develop Mars Artisan (premium nougat + local flavors in each market) for Indonesia/Philippines. Partner with luxury retailers. 60%+ margins.', 'Bain Asian Confectionery 2024'),
('Nestlé Confectionery', 'growth_adjacency', 'Asian Confectionery Premium Tier', 'Bain: Asian confectionery market $28B, growing 11% CAGR. India/Indonesia middle-class purchasing premium chocolate 40% more than 5 years ago. Local brands dominating; Western premium brands (Lindt, Ferrero) underpenetrated in value tiers.', '$6.2B', 7.9, 'Nestlé KitKat iconic globally but positioned value. Premium KitKat variants exist but not optimized for Asia gifting market.', 'Expand KitKat Prestige (premium flavors: matcha, yuzu, mango) exclusively in Asia. Limited editions drive scarcity/gifting narrative. 65% margins.', 'Bain Asian Confectionery 2024'),

-- Gap 3: Sustainability Premium
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Ferrero', 'growth_adjacency', 'Sustainable/Ethical Premium Positioning', 'McKinsey: 73% consumers willing to pay premium for sustainable snacks. Ferrero (Nutella) faces palm oil scrutiny; opportunity to differentiate via certified sustainable sourcing + transparency.', '$2.1B', 7.6, 'Ferrero owns premium positioning but vulnerable on sustainability. Consumers conflate luxury + ethical. Competitors (Tony''s Chocolonely) gaining share on ethics.', 'Launch Ferrero Pure (certified sustainable, ethical sourcing, transparent supply chain) at 40% premium. DTC + premium retail. Sustainability storytelling central.', 'McKinsey Sustainable Snacking 2024'),
('Lindt', 'growth_adjacency', 'Sustainable/Ethical Premium Positioning', 'McKinsey: 73% consumers willing to pay premium for sustainable snacks. Ferrero (Nutella) faces palm oil scrutiny; opportunity to differentiate via certified sustainable sourcing + transparency.', '$2.1B', 7.6, 'Lindt premium but not sustainability leader. Opportunity to own "ethical luxury" positioning vs. Ferrero/Godiva.', 'Develop Lindt Heritage (certified sustainable cocoa, fair trade, carbon-neutral) at premium tier. Emphasize Swiss craftsmanship + ethics. Premium gift positioning.', 'McKinsey Sustainable Snacking 2024'),
('Hershey', 'growth_adjacency', 'Sustainable/Ethical Premium Positioning', 'McKinsey: 73% consumers willing to pay premium for sustainable snacks. Ferrero (Nutella) faces palm oil scrutiny; opportunity to differentiate via certified sustainable sourcing + transparency.', '$2.1B', 7.6, 'Hershey mass-market but opportunity to create premium sustainable sub-brand. American heritage + ethics = differentiation.', 'Create Hershey Heritage Craft (artisanal, sustainable, single-origin) at $6.99/bar. DTC + Whole Foods. Premium gift market.', 'McKinsey Sustainable Snacking 2024');

-- ============ PERSONAL CARE & BEAUTY (HBR: Beauty DTC Disruption, McKinsey: Personalization) ============

-- Gap 1: Clinical DTC Skincare
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Olay', 'growth_adjacency', 'Clinical DTC Personalized Skincare', 'HBR: Beauty DTC disruptors (Glossier, Olaplex, Curology) growing 40% CAGR by owning personalization + community. Traditional incumbents (Olay, Neutrogena) losing share to DTC. Personalization + clinical efficacy = premium pricing.', '$7.8B', 8.3, 'Olay strong in mass retail but absent from DTC/personalization trend. Opportunity to own "clinical DTC" positioning. Consumers pay 60% premium for personalized skincare.', 'Launch Olay+ digital (AI skin assessment + personalized serum + subscription). DTC-only, $49/mo. Leverage Procter & Gamble data infrastructure. Target millennial women.', 'HBR Beauty DTC Disruption 2024'),
('Neutrogena', 'growth_adjacency', 'Clinical DTC Personalized Skincare', 'HBR: Beauty DTC disruptors (Glossier, Olaplex, Curology) growing 40% CAGR by owning personalization + community. Traditional incumbents (Olay, Neutrogena) losing share to DTC. Personalization + clinical efficacy = premium pricing.', '$7.8B', 8.3, 'Neutrogena dermatologist-approved but retail-bound. DTC opportunity to own "clinical accessible" positioning without luxury markup. Community + science.', 'Develop Neutrogena Digital (app-guided routine + monthly delivery) at $39/mo. Target acne-prone Gen-Z. Leverage dermatologist trust for clinical positioning.', 'HBR Beauty DTC Disruption 2024'),
('Dove', 'growth_adjacency', 'Clinical DTC Personalized Skincare', 'HBR: Beauty DTC disruptors (Glossier, Olaplex, Curology) growing 40% CAGR by owning personalization + community. Traditional incumbents (Olay, Neutrogena) losing share to DTC. Personalization + clinical efficacy = premium pricing.', '$7.8B', 8.3, 'Dove "real beauty" brand resonates with Gen-Z but not positioned for clinical/personalization. DTC + community opportunity.', 'Create Dove Science (personalized skincare based on microbiome testing) at $45/mo. Partner with labs. Position as "real skin science" aligned with brand ethos.', 'HBR Beauty DTC Disruption 2024'),

-- Gap 2: Male Grooming Expansion
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Gillette', 'market_gap', 'Male Skincare (beyond shaving)', 'Euromonitor: Male skincare market growing 18% CAGR globally, 28% in Asia. Category expanding beyond razors (moisturizers, cleansers, serums). Gillette owns shaving but not skincare.', '$4.2B', 8.0, 'Gillette dominates razors but absent from skincare. Male consumers willing to spend 3x on skincare if bundled with shaving routine. Opportunity to own "male grooming ecosystem".', 'Launch Gillette Men''s Skincare line (face wash, moisturizer, serum) at premium tier. Bundle with razor subscription. Target male 20-40. Partner with barber shops.', 'Euromonitor Male Skincare 2024'),
('L''Oréal', 'market_gap', 'Male Skincare (beyond shaving)', 'Euromonitor: Male skincare market growing 18% CAGR globally, 28% in Asia. Category expanding beyond razors (moisturizers, cleansers, serums). Gillette owns shaving but not skincare.', '$4.2B', 8.0, 'L''Oréal owns luxury skincare but male line underdeveloped. Male consumers perceive skincare as feminine; opportunity to destigmatize + monetize.', 'Develop L''Oréal Men Expert Premium (clinically proven, masculine branding) at $35/50ml. Launch via male-focused retailers (Dick''s, Lululemon). Fitness/wellness positioning.', 'Euromonitor Male Skincare 2024'),
('Estée Lauder', 'market_gap', 'Male Skincare (beyond shaving)', 'Euromonitor: Male skincare market growing 18% CAGR globally, 28% in Asia. Category expanding beyond razors (moisturizers, cleansers, serums). Gillette owns shaving but not skincare.', '$4.2B', 8.0, 'Estée Lauder luxury but historically female-focused. Male luxury skincare (La Roche-Posay Men) emerging. Premium opportunity.', 'Create Lauder Men Prestige (anti-aging serum + moisturizer set) at $150. Position as "masculine luxury". DTC + Sephora. Target affluent male 35-55.', 'Euromonitor Male Skincare 2024'),

-- Gap 3: Clean Beauty Premiumization
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Olay', 'growth_adjacency', 'Clean Beauty Premium Tier', 'McKinsey: Clean beauty segment growing 35% CAGR. Consumers willing to pay 2-3x for "clean" formulations (no parabens, sulfates, synthetic chemicals). Traditional brands launching clean sub-brands (Origins, CeraVe Clean).', '$3.5B', 7.7, 'Olay mass-market perception conflicts with clean beauty positioning. Opportunity: create "Olay Pure" (clean formulations) at premium tier without cannibalization.', 'Launch Olay Pure (clean, dermatologist-tested, vegan) at $24/oz. Separate branding, digital-first. Target conscious millennials. 65% margins.', 'McKinsey Clean Beauty 2024'),
('Revlon', 'growth_adjacency', 'Clean Beauty Premium Tier', 'McKinsey: Clean beauty segment growing 35% CAGR. Consumers willing to pay 2-3x for "clean" formulations (no parabens, sulfates, synthetic chemicals). Traditional brands launching clean sub-brands (Origins, CeraVe Clean).', '$3.5B', 7.7, 'Revlon facing bankruptcy but opportunity in clean cosmetics. Clean makeup (Kosas, Tower 28) emerging category. Revlon scale + clean positioning = advantage.', 'Develop Revlon Clean Colour (clean makeup formulations) at 40% premium. Partner with Sephora. Target Gen-Z makeup consumers willing to pay for clean.', 'McKinsey Clean Beauty 2024'),
('Maybelline', 'growth_adjacency', 'Clean Beauty Premium Tier', 'McKinsey: Clean beauty segment growing 35% CAGR. Consumers willing to pay 2-3x for "clean" formulations (no parabens, sulfates, synthetic chemicals). Traditional brands launching clean sub-brands (Origins, CeraVe Clean).', '$3.5B', 7.7, 'Maybelline owned by L''Oréal, positioned mass-market. Clean cosmetics trend bypassing mass market. Opportunity to own "accessible clean" positioning.', 'Launch Maybelline Pure (clean makeup, sustainable packaging) at $8.99. Differentiate as "clean at drugstore price". Amazon + Target. Volume play with margin benefit.', 'McKinsey Clean Beauty 2024');

-- ============ HOUSEHOLD & CLEANING (Bain: Eco-Premium, McKinsey: B2B Commercial) ============

-- Gap 1: Eco-Premium Positioning
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Tide', 'growth_adjacency', 'Eco-Premium Laundry Detergent', 'Bain: Eco-premium cleaning growing 22% CAGR. Consumers willing to pay 50% premium for sustainable + effective. Traditional detergent market flat; growth entirely in eco-premium segment (Method, Seventh Generation).', '$3.8B', 7.9, 'Tide dominates mass market but absent from eco-premium. Opportunity to create premium eco sub-brand without cannibalizing Tide core.', 'Launch Tide Pure (plant-based enzymes, biodegradable, recyclable packaging) at $6.99/bottle. DTC + Whole Foods. Target eco-conscious affluent consumers.', 'Bain Eco-Premium Household 2024'),
('Clorox', 'growth_adjacency', 'Eco-Premium Laundry Detergent', 'Bain: Eco-premium cleaning growing 22% CAGR. Consumers willing to pay 50% premium for sustainable + effective. Traditional detergent market flat; growth entirely in eco-premium segment (Method, Seventh Generation).', '$3.8B', 7.9, 'Clorox owns disinfectant but not eco-laundry. Bleach perception conflicts with clean beauty movement. Opportunity: separate eco brand.', 'Create Clorox Natural (plant-based, effective, hypoallergenic) at $5.99. Position as "natural disinfection". Target families with allergies + eco-conscious households.', 'Bain Eco-Premium Household 2024'),
('Method', 'growth_adjacency', 'Eco-Premium Laundry Detergent', 'Bain: Eco-premium cleaning growing 22% CAGR. Consumers willing to pay 50% premium for sustainable + effective. Traditional detergent market flat; growth entirely in eco-premium segment (Method, Seventh Generation).', '$3.8B', 7.9, 'Method owns eco-positioning but laundry detergent underdeveloped vs. all-purpose. Opportunity to expand laundry line aggressively.', 'Expand Method Laundry (multiple scents, formulation for sensitive skin + performance) at $6.49. Aggressive digital marketing. Target DTC + Amazon.', 'Bain Eco-Premium Household 2024'),

-- Gap 2: B2B Commercial Cleaning
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Lysol', 'market_gap', 'B2B Commercial Disinfection', 'McKinsey: Commercial cleaning market $18B, growing 12% post-COVID. B2B buyers (offices, schools, hospitals) seeking integrated solutions + sustainability. Lysol strong in consumer but weak in B2B channel.', '$5.6B', 8.2, 'Post-COVID, B2B disinfection demand sustained. Lysol has brand recognition but no B2B sales force. Competitors (Ecolab, Diversey) dominating B2B. Opportunity: build B2B channel.', 'Launch Lysol B2B (commercial-grade, concentrated, dilution tracking) with direct sales to facilities management companies. Target schools + offices. 45%+ margins.', 'McKinsey B2B Commercial Cleaning 2024'),
('Clorox', 'market_gap', 'B2B Commercial Disinfection', 'McKinsey: Commercial cleaning market $18B, growing 12% post-COVID. B2B buyers (offices, schools, hospitals) seeking integrated solutions + sustainability. Lysol strong in consumer but weak in B2B channel.', '$5.6B', 8.2, 'Clorox has B2B presence but fragmented. Opportunity to consolidate bleach + disinfectant + eco lines into integrated B2B offering.', 'Develop Clorox Commercial Suite (bleach, disinfectant, eco options) with facility management portal + ordering system. Direct sales to large accounts.', 'McKinsey B2B Commercial Cleaning 2024'),
('Dawn', 'market_gap', 'B2B Commercial Disinfection', 'McKinsey: Commercial cleaning market $18B, growing 12% post-COVID. B2B buyers (offices, schools, hospitals) seeking integrated solutions + sustainability. Lysol strong in consumer but weak in B2B channel.', '$5.6B', 8.2, 'Dawn dominates dishwashing consumer but no B2B commercial offering. Schools/cafeterias use generic brands. Opportunity to dominate institutional dishwashing.', 'Launch Dawn Commercial (industrial-size, cost-per-wash efficiency data) targeting schools + institutional kitchens. Sales to food service distributors.', 'McKinsey B2B Commercial Cleaning 2024'),

-- Gap 3: Subscription + Efficiency Services
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Tide', 'growth_adjacency', 'Laundry Subscription + Smart Dispensing', 'Bain: Subscription cleaning services growing 18% CAGR. Consumers adopting smart dispensers (Tide Auto Dispense). Bundling detergent + service = retention + data opportunity.', '$2.1B', 7.8, 'Tide Auto Dispense exists but not positioned as subscription. Recurring revenue + consumer data = strategic advantage. Opportunity: Tide subscription ecosystem.', 'Launch Tide Refresh (auto-refill subscription + smart washer integration + laundry optimization app) at $15/mo. Recurring revenue model. Target connected home segment.', 'Bain Laundry Services 2024'),
('Henkel', 'growth_adjacency', 'Laundry Subscription + Smart Dispensing', 'Bain: Subscription cleaning services growing 18% CAGR. Consumers adopting smart dispensers (Tide Auto Dispense). Bundling detergent + service = retention + data opportunity.', '$2.1B', 7.8, 'Henkel (Persil) strong in Europe but lagging US digital/subscription. Opportunity to own subscription laundry in Europe + expand US.', 'Develop Persil Plus (subscription laundry service + smart dispenser + optimization) in Europe. Target affluent households. Recurring revenue model.', 'Bain Laundry Services 2024'),
('Surf', 'growth_adjacency', 'Laundry Subscription + Smart Dispensing', 'Bain: Subscription cleaning services growing 18% CAGR. Consumers adopting smart dispensers (Tide Auto Dispense). Bundling detergent + service = retention + data opportunity.', '$2.1B', 7.8, 'Surf owned by Unilever but value-positioned. Subscription opportunity for budget-conscious segment: affordable subscription access.', 'Launch Surf Smart (budget subscription laundry service + simple dispenser) at $9/mo. Target budget households. High volume, solid margins.', 'Bain Laundry Services 2024');

-- ============ QSR & FOOD SERVICE (Bain: Digital QSR, Harvard: Labor & Delivery Models) ============

-- Gap 1: Delivery-First Ghost Kitchen Model
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('McDonald''s', 'growth_adjacency', 'Delivery-Optimized Menu + Ghost Kitchens', 'Harvard Business Review: Post-COVID QSR growth driven by delivery-first models (DoorDash, Uber Eats). Traditional QSRs losing share to ghost kitchens. Opportunity: McDonald''s scale + brand into delivery-optimized ghost kitchen network.', '$6.8B', 8.4, 'McDonald''s dominates retail but delivery cannibalization risk underexplored. Opportunity: optimize menu for delivery (heat-retention, packaging), launch ghost kitchen footprint in delivery-dense urban areas.', 'Launch McDelivery Kitchen (optimized delivery menu, ghost kitchen model) in top 20 metro areas. Exclusive delivery-only items (McWraps, salads for health positioning). Leverage scale for logistics.', 'Harvard QSR Digital Transformation 2024'),
('Subway', 'growth_adjacency', 'Delivery-Optimized Menu + Ghost Kitchens', 'Harvard Business Review: Post-COVID QSR growth driven by delivery-first models (DoorDash, Uber Eats). Traditional QSRs losing share to ghost kitchens. Opportunity: McDonald''s scale + brand into delivery-optimized ghost kitchen network.', '$6.8B', 8.4, 'Subway franchise model suits delivery. Opportunity: build ghost kitchen network (no front-of-house costs) owned by Subway (not franchisees) in delivery hotspots.', 'Create Subway Digital (ghost kitchens in dense delivery zones, optimized menu for speed) with corporate ownership. Target college towns + urban centers. 35%+ unit economics.', 'Harvard QSR Digital Transformation 2024'),
('Domino''s', 'growth_adjacency', 'Delivery-Optimized Menu + Ghost Kitchens', 'Harvard Business Review: Post-COVID QSR growth driven by delivery-first models (DoorDash, Uber Eats). Traditional QSRs losing share to ghost kitchens. Opportunity: McDonald''s scale + brand into delivery-optimized ghost kitchen network.', '$6.8B', 8.4, 'Domino''s delivery leader but retail footprint underutilized for delivery-only ghost kitchen concept. Scale existing supply chain for ghost kitchen expansion.', 'Develop Domino''s Express (delivery-only concept in delivery hotspots, shared supply chain) with 50% lower rent. Rapid unit growth strategy. Target 500 units in 3 years.', 'Harvard QSR Digital Transformation 2024'),

-- Gap 2: Health-Conscious Premiumization
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('McDonald''s', 'growth_adjacency', 'Premium Health-Focused QSR Line', 'McKinsey: Health-conscious dining growing 28% CAGR. Consumers trading up from fast food to "fast casual healthy" (Chipotle, Shake Shack, Sweetgreen). McDonald''s losing affluent consumers to premiumization.', '$4.2B', 7.8, 'McDonald''s losing market share to Chipotle/Panera in affluent segment. Opportunity: create premium health line without cannibalizing core.', 'Launch McDonald''s Fresh (salads, bowls, plant-based, calorie-transparent) at premium tier ($12-15) in affluent locations. Separate branding, distinct positioning from core.', 'McKinsey Premium QSR 2024'),
('KFC', 'growth_adjacency', 'Premium Health-Focused QSR Line', 'McKinsey: Health-conscious dining growing 28% CAGR. Consumers trading up from fast food to "fast casual healthy" (Chipotle, Shake Shack, Sweetgreen). McDonald''s losing affluent consumers to premiumization.', '$4.2B', 7.8, 'KFC fried chicken perception conflicts with health trends. Opportunity: launch premium rotisserie/grilled chicken line to compete with Chick-fil-A + Popeyes in health segment.', 'Develop KFC Prime (rotisserie + grilled chicken, health positioning) at premium tier. Leverage KFC scale + chicken expertise. Target affluent + health-conscious.', 'McKinsey Premium QSR 2024'),
('Wendy''s', 'growth_adjacency', 'Premium Health-Focused QSR Line', 'McKinsey: Health-conscious dining growing 28% CAGR. Consumers trading up from fast food to "fast casual healthy" (Chipotle, Shake Shack, Sweetgreen). McDonald''s losing affluent consumers to premiumization.', '$4.2B', 7.8, 'Wendy''s "fresh, never frozen" positioning partially aligns with health. Opportunity: emphasize quality + health in premium line targeting affluent burger seekers.', 'Launch Wendy''s Craft (premium grass-fed beef, artisanal toppings, clean label) at $14-16. Position vs. Five Guys but with Wendy''s scale advantage. Target affluent suburbs.', 'McKinsey Premium QSR 2024'),

-- Gap 3: Automation + Labor Cost Mitigation
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Chipotle', 'growth_adjacency', 'Kitchen Automation + Labor Efficiency', 'Bain: QSR labor costs rising 15% CAGR. Automation (Flippy robots, conveyor grills, robotic arms) reducing labor dependency. Chipotle testing automation; early mover advantage in cost structure.', '$2.8B', 8.0, 'Chipotle testing automation but limited scale. Opportunity: aggressive automation deployment across chain to offset labor inflation + improve margins.', 'Roll out Chipotle Automated (Flippy grill + robotic burrito assembly in 200+ units) within 2 years. Labor reduction 30-40%. Marketing: "efficiency for speed + consistency".', 'Bain QSR Automation 2024'),
('Taco Bell', 'growth_adjacency', 'Kitchen Automation + Labor Efficiency', 'Bain: QSR labor costs rising 15% CAGR. Automation (Flippy robots, conveyor grills, robotic arms) reducing labor dependency. Chipotle testing automation; early mover advantage in cost structure.', '$2.8B', 8.0, 'Taco Bell menu flexibility suits automation (modular components). Opportunity: lead automation adoption in quick-service Mexican to offset wage inflation.', 'Deploy Taco Bell Automated (modular burrito + taco assembly lines) in 150+ units. Labor reduction 35%. Margin expansion 500bps. Franchise model advantage.', 'Bain QSR Automation 2024'),
('Pizza Hut', 'growth_adjacency', 'Kitchen Automation + Labor Efficiency', 'Bain: QSR labor costs rising 15% CAGR. Automation (Flippy robots, conveyor grills, robotic arms) reducing labor dependency. Chipotle testing automation; early mover advantage in cost structure.', '$2.8B', 8.0, 'Pizza Hut automation trail: pizza assembly + topping distribution. Opportunity: robotics deployment to reduce labor dependency + improve consistency.', 'Launch Pizza Hut Automated (robotic pizza assembly + oven systems) in 100+ units. Labor reduction 25-30%. Emphasize speed + consistency in delivery model.', 'Bain QSR Automation 2024');

-- ============ DAIRY & PACKAGED FOOD (Mintel: Plant-Based Surge, Bain: Emerging Markets Food) ============

-- Gap 1: Plant-Based Adjacencies
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Tyson Foods', 'growth_adjacency', 'Plant-Based Protein Adjacency', 'Mintel: Plant-based meat growing 28% CAGR. Meat incumbents (Tyson, Perdue) launching plant-based lines (Beyond Meat partnerships, in-house brands). First-mover meat brands winning in meat-alternative segment.', '$2.9B', 8.1, 'Tyson dominates poultry but absent from plant-based. Opportunity: leverage protein manufacturing expertise + distribution into plant-based chicken alternative.', 'Launch Tyson Plant-Based Chicken (pea protein, chicken texture/taste parity) at price parity to conventional. Leverage existing poultry distribution to retailers.', 'Mintel Plant-Based Meat 2024'),
('Ben & Jerry''s', 'growth_adjacency', 'Plant-Based Adjacency (Dairy-Free Ice Cream)', 'Mintel: Plant-based ice cream growing 35% CAGR. Consumers willing to pay 20% premium for "clean" dairy-free options. Traditional ice cream flat; all growth in plant-based + premium segments.', '$1.8B', 7.9, 'Ben & Jerry''s premium positioning but limited plant-based portfolio vs. competitors (Oatly, So Delicious). Opportunity to own "premium dairy-free" positioning.', 'Expand Ben & Jerry''s Dairy-Free line (coconut, oat, almond bases) with premium flavors. Target affluent health-conscious consumers. Premium pricing maintained.', 'Mintel Plant-Based Ice Cream 2024'),
('Nestlé Food', 'growth_adjacency', 'Plant-Based Adjacency (Dairy-Free Ice Cream)', 'Mintel: Plant-based ice cream growing 35% CAGR. Consumers willing to pay 20% premium for "clean" dairy-free options. Traditional ice cream flat; all growth in plant-based + premium segments.', '$1.8B', 7.9, 'Nestlé owns premium ice cream (Haagen-Dazs) but underexploited in plant-based. Opportunity: Haagen-Dazs Dairy-Free at ultra-premium tier.', 'Create Häagen-Dazs Plant-Based (organic coconut/almond, premium positioning) at $8/pint. Limited distribution (Whole Foods, premium grocery). Ultra-premium strategy.', 'Mintel Plant-Based Ice Cream 2024'),

-- Gap 2: Emerging Market Food Localization
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Kraft Heinz', 'growth_adjacency', 'Localized Asian Condiment + Sauce', 'Bain: Asian condiment market $8.2B, growing 9% CAGR. Local brands dominate but Western premium brands entering (Heinz ketchup in India). Opportunity: Kraft Heinz localized sauces in India/Vietnam/Indonesia.', '$1.6B', 7.7, 'Kraft Heinz global condiments but limited Asia localization. Opportunity: acquire local sauce brands or develop hybrid (Heinz + local flavors) for premium positioning.', 'Develop Heinz Asian Fusion (Heinz ketchup + Asian flavors: chili, soy, ginger variations) for India/Vietnam/Indonesia. Premium positioning. Partner with modern retail.', 'Bain Asian Condiments 2024'),
('General Mills', 'growth_adjacency', 'Localized Asian Condiment + Sauce', 'Bain: Asian condiment market $8.2B, growing 9% CAGR. Local brands dominate but Western premium brands entering (Heinz ketchup in India). Opportunity: Kraft Heinz localized sauces in India/Vietnam/Indonesia.', '$1.6B', 7.7, 'General Mills breakfast focus but condiment entry possible via acquisition. Asian breakfast growing (local sauces, condiments). Opportunity to bundle breakfast + sauces.', 'Acquire Asian sauce brands (Vietnam, Indonesia) and bundle with General Mills cereals/oats. Localized breakfast experiences targeting modernizing middle-class.', 'Bain Asian Condiments 2024'),
('ConAgra', 'growth_adjacency', 'Localized Asian Condiment + Sauce', 'Bain: Asian condiment market $8.2B, growing 9% CAGR. Local brands dominate but Western premium brands entering (Heinz ketchup in India). Opportunity: Kraft Heinz localized sauces in India/Vietnam/Indonesia.', '$1.6B', 7.7, 'ConAgra owns Hunt''s tomato products but limited Asian presence. Opportunity: localized Asian sauces (chili, tamarind, coconut-based) to leverage manufacturing scale.', 'Launch ConAgra Asian Sauces (localized flavor blends for India/Philippines/Thailand) via modern retail. Leverage manufacturing efficiency. 45% margins.', 'Bain Asian Condiments 2024'),

-- Gap 3: Subscription + Meal Solutions
INSERT INTO brand_market_opportunities (brand_name, gap_type, gap_name, gap_description, market_size, opportunity_score, why_opportunity, brand_recommendation, source_reference) VALUES
('Campbells Soup', 'growth_adjacency', 'Meal Kit + Subscription Integration', 'Mintel: Meal kit subscriptions growing 12% CAGR. Traditional food brands (Campbell''s) integrating subscription models for recurring revenue + consumer data.', '$1.2B', 7.6, 'Campbell''s iconic comfort but declining volume. Subscription meal kit opportunity: Campbell''s base + proteins/veggies bundled as weekly meal solution.', 'Launch Campbell''s Meal Prep (weekly subscription meal kits using Campbell''s soups + proteins + produce) at $35/week. DTC + Amazon Fresh. Recurring revenue model.', 'Mintel Meal Kit Subscriptions 2024'),
('Unilever Food', 'growth_adjacency', 'Meal Kit + Subscription Integration', 'Mintel: Meal kit subscriptions growing 12% CAGR. Traditional food brands (Campbell''s) integrating subscription models for recurring revenue + consumer data.', '$1.2B', 7.6, 'Unilever owns diverse food brands (Hellmann''s, Knorr). Opportunity: bundle into meal kit subscription leveraging multi-brand portfolio.', 'Develop Unilever Meals (curated weekly recipes using Hellmann''s, Knorr, other brands + fresh ingredients) at $42/week. DTC model. Subscription focus.', 'Mintel Meal Kit Subscriptions 2024'),
('Kellogg''s', 'growth_adjacency', 'Meal Kit + Subscription Integration', 'Mintel: Meal kit subscriptions growing 12% CAGR. Traditional food brands (Campbell''s) integrating subscription models for recurring revenue + consumer data.', '$1.2B', 7.6, 'Kellogg''s breakfast brand but meal kit opportunity beyond breakfast. Bundle Kellogg''s + proteins + produce as weekly breakfast + lunch subscriptions.', 'Launch Kellogg''s Mornings (breakfast + lunch subscription meal kit) at $38/week. Target busy professionals. Leverage Kellogg''s brand trust for meal solutions.', 'Mintel Meal Kit Subscriptions 2024');

-- Verify deployment
SELECT COUNT(*) as total_opportunities FROM brand_market_opportunities;
