"""
Shopping History Service — Track all receipts with merchant, date, amount, location.
"""
import library as lib
from datetime import datetime
import json

def ensure_shopping_history_table():
    """Create shopping_history table if it doesn't exist."""
    try:
        sb = lib._sb()
        # Try to query - if table doesn't exist, it will error
        sb.table("shopping_history").select("id").limit(1).execute()
        print("[shopping-history] Table exists")
        return True
    except:
        print("[shopping-history] Table doesn't exist yet. Create manually in Supabase SQL:")
        print("""
        CREATE TABLE shopping_history (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          from_number TEXT NOT NULL,
          merchant TEXT NOT NULL,
          amount NUMERIC(10,2),
          shop_date DATE,
          shop_time TIME,
          location TEXT,
          address TEXT,
          postcode TEXT,
          category TEXT,
          items JSONB,
          receipt_id TEXT,
          source TEXT,
          created_at TIMESTAMP DEFAULT NOW(),
          updated_at TIMESTAMP DEFAULT NOW()
        );

        CREATE INDEX idx_shopping_from_number ON shopping_history(from_number);
        CREATE INDEX idx_shopping_date ON shopping_history(shop_date DESC);
        CREATE INDEX idx_shopping_merchant ON shopping_history(merchant);
        """)
        return False


def store_receipt(from_number: str, merchant: str, amount: float, shop_date: str,
                  location: str = "", address: str = "", postcode: str = "",
                  category: str = "", items: list = None, receipt_id: str = ""):
    """
    Store a receipt in shopping_history table (with deduplication).

    Args:
        from_number: User's WhatsApp number (plain or whatsapp:)
        merchant: Merchant name (e.g., "Costa Coffee")
        amount: Amount spent (£)
        shop_date: Date of purchase (YYYY-MM-DD)
        location: Location (e.g., "Virginia Water" or "GU25 4AA")
        address: Full address if available
        postcode: UK postcode
        category: Category (Coffee & Lunch, Groceries, etc.)
        items: List of items purchased
        receipt_id: ID from wa_saves or receipts table
    """
    try:
        sb = lib._sb()
        plain_number = from_number.replace("whatsapp:", "").strip()

        # Check if already stored (by receipt_id first)
        if receipt_id:
            existing = sb.table("shopping_history").select("id") \
                .eq("from_number", plain_number) \
                .eq("receipt_id", receipt_id) \
                .execute().data or []
            if existing:
                print(f"[shopping-history] Already stored (receipt_id): {receipt_id}")
                return True

        # Check by merchant + date + amount (catch duplicates without receipt_id)
        # Round amount to 2 decimals for comparison
        amount_rounded = round(float(amount), 2) if amount else 0
        existing = sb.table("shopping_history").select("id") \
            .eq("from_number", plain_number) \
            .eq("merchant", merchant) \
            .eq("shop_date", shop_date) \
            .execute().data or []

        if existing:
            # Check if amount matches (within 1p tolerance for rounding)
            for row in existing:
                existing_amount = round(float(row.get("amount", 0)), 2)
                if abs(existing_amount - amount_rounded) < 0.01:
                    print(f"[shopping-history] Already stored (duplicate): {merchant} £{amount} on {shop_date}")
                    return True

        # Store (no duplicate found)
        sb.table("shopping_history").insert({
            "from_number": plain_number,
            "merchant": merchant,
            "amount": amount_rounded,
            "shop_date": shop_date,
            "location": location,
            "address": address,
            "postcode": postcode,
            "category": category,
            "items": json.dumps(items) if items else None,
            "receipt_id": receipt_id,
            "source": "receipt_scan"
        }).execute()

        print(f"[shopping-history] Stored: {merchant} £{amount} on {shop_date}")
        return True

    except Exception as e:
        print(f"[shopping-history] Error storing receipt: {e}")
        return False


def get_shopping_history(from_number: str, days_back: int = 30, limit: int = 100):
    """Get user's shopping history."""
    try:
        sb = lib._sb()
        plain_number = from_number.replace("whatsapp:", "").strip()

        rows = sb.table("shopping_history").select("*") \
            .eq("from_number", plain_number) \
            .order("shop_date", desc=True) \
            .limit(limit) \
            .execute().data or []

        return rows
    except Exception as e:
        print(f"[shopping-history] Error fetching: {e}")
        return []


def get_retailer_list(from_number: str, days_back: int = 30):
    """Get unique retailers with totals and visit counts."""
    try:
        sb = lib._sb()
        plain_number = from_number.replace("whatsapp:", "").strip()

        rows = sb.table("shopping_history").select("*") \
            .eq("from_number", plain_number) \
            .order("shop_date", desc=True) \
            .execute().data or []

        # Group by merchant + location
        retailers = {}
        for row in rows:
            key = f"{row.get('merchant', '')}|{row.get('postcode', '') or row.get('location', '')}"
            if key not in retailers:
                retailers[key] = {
                    "merchant": row.get('merchant', ''),
                    "location": row.get('postcode', '') or row.get('location', ''),
                    "address": row.get('address', ''),
                    "postcode": row.get('postcode', ''),
                    "category": row.get('category', ''),
                    "visits": 0,
                    "total_spent": 0,
                    "last_visited": row.get('shop_date', '')
                }
            retailers[key]['visits'] += 1
            retailers[key]['total_spent'] += float(row.get('amount', 0))

        return list(retailers.values())

    except Exception as e:
        print(f"[shopping-history] Error getting retailers: {e}")
        return []
